global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["192.168.0.31:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["192.168.0.31:9100"]

remote_write:
  - url: "<Your Prometheus remote_write endpoint>"
    basic_auth:
      username: "<Your Grafana Username>"
      password: "<Your Grafana API key>"
